### ISSUE TITLE
No such file or directory: 'deep_sort_pytorch/deep_sort/deep/checkpoint/ckpt.t7'

### ISSUE THREAD

**Issue by mradamhoward** [winston1214/Car_Counting#2]
Hi,

Is there a solution to the error in the title? It might be that my GPU doesn't have enough memory? Or is there a config I'm missing? I follows the steps you laid out in the Readme. Ubuntu is my OS.

**Comment by mradamhoward** [comment]
Hi thanks I got it working, thank you for this great project, you should keep working on it to improve it.. .

**Comment by winston1214** [comment]
> Hi thanks I got it working, thank you for this great project, you should keep working on it to improve it.. .

Thank you for your interest in this project. This project is an ongoing project and is continuously developing. I will update README about the modifications later. Thank you.
